PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?s  ?title  WHERE {
  GRAPH <http://risis.eu/cordisH2020> {
    {
      SELECT DISTINCT ?s WHERE {
        GRAPH <http://risis.eu/cordisH2020> {
          ?s rdf:type <http://risis.eu/cordisH2020/vocab/SignedGrantAgreement> .
          ?s <http://risis.eu/cordisH2020/vocab/coordinatorCountry> ?v1.
          ?s <http://risis.eu/cordisH2020/vocab/fundingScheme> ?v2.
          ?s <http://risis.eu/cordisH2020/vocab/program> ?v3.
          FILTER (str(?v1) IN ("""NL""") && iri(?v2) IN (<http://risis.eu/cordisH2020/resource/fundingScheme_RIA>,<http://risis.eu/cordisH2020/resource/fundingScheme_ERC-STG>) && iri(?v3) IN (<http://risis.eu/cordisH2020/resource/program_H2020-EU.3.1.>,<http://risis.eu/cordisH2020/resource/program_H2020-EU.2.1.1.>)) 
        } 
      }
      LIMIT 20 OFFSET 0
    }
    OPTIONAL {
      ?s <http://purl.org/dc/terms/title> ?title .
    }     
  } 
}
